replicaCount: 2

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: "17"

service:
  type: ClusterIP
  port: 5432

postgresql:
  database: a8sdb
  username: a8s
  password: strongpassword

env:
  - name: POSTGRES_DB
    value: a8s_db

  - name: POSTGRES_USER
    value: autonomous

  - name: POSTGRES_PASSWORD
    value: AutonomousStrongPassword

  - name: PGDATA
    value: /var/lib/postgresql/data/pgdata

volumeMounts:
  - name: postgres-storage
    mountPath: /var/lib/postgresql/data

volumes:
  - name: postgres-storage
    persistentVolumeClaim:
      claimName: postgres-pvc

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"

  limits:
    memory: "1Gi"
    cpu: "500m"

livenessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 5432
  initialDelaySeconds: 10
  periodSeconds: 10

ingress:
  enabled: false

autoscaling:
  enabled: false

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

persistence:
  enabled: true
  storageClass: longhorn
  size: 10Gi